INSERT INTO trim_tier_reference (make, model, gen_start, gen_end, trim, tier, tier_name, top_engine, audio_brand, expected_parts, notes, cult, transmission, diesel) VALUES
('Dodge', 'Magnum', 2005, 2008, 'SE', 1, 'base', '2.7L V6', '', '', '2.7L V6. Base wagon.', false, 'Automatic', false),
('Dodge', 'Magnum', 2005, 2008, 'SXT', 2, 'mid', '3.5L V6', '', 'Power seats, heated seats possible', '', false, 'Automatic', false),
('Dodge', 'Magnum', 2005, 2008, 'R/T', 3, 'premium', '5.7L HEMI', 'Infinity', 'Infinity amp, HEMI ECM, heated leather, moonroof', 'HEMI wagon.', false, 'Automatic', false),
('Dodge', 'Magnum', 2005, 2008, 'SRT-8', 4, 'performance', '6.1L HEMI', 'Kicker', 'Kicker amp, SRT ECM, Brembo brakes, adaptive suspension', 'SRT wagon. Rare and cult.', true, 'Automatic', false),
('Chrysler', 'PT Cruiser', 2001, 2010, 'Base', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Chrysler', 'PT Cruiser', 2001, 2010, 'Touring', 2, 'mid', '2.4L I4', '', 'Power windows, cruise, A/C, alloy wheels', '', false, 'Automatic', false),
('Chrysler', 'PT Cruiser', 2001, 2010, 'Limited', 3, 'premium', '2.4L I4', 'Infinity', 'Infinity amp, heated leather, moonroof, chrome trim', '', false, 'Automatic', false),
('Chrysler', 'PT Cruiser', 2001, 2010, 'GT Turbo', 4, 'performance', '2.4L Turbo I4 (230hp)', '', 'Turbo ECM, turbo, intercooler, sport suspension, 230hp', 'Turbo PT. SRT-4 engine.', true, '5-speed Manual', false),
('Chrysler', 'PT Cruiser', 2001, 2010, 'Convertible', 2, 'mid', '2.4L I4', '', 'Power top, Turbo available', '', false, 'Automatic', false),
('Dodge', 'Neon', 2000, 2005, 'SE', 1, 'base', '2.0L I4', '', '', '', false, 'Automatic', false),
('Dodge', 'Neon', 2000, 2005, 'SXT', 2, 'mid', '2.0L I4', '', 'Power windows, cruise, A/C', '', false, 'Automatic', false),
('Dodge', 'Neon', 2000, 2005, 'SRT-4', 4, 'performance', '2.4L Turbo I4 (230hp)', '', 'Turbo ECM, turbo, intercooler, LSD, sport suspension, AGR turbo, sport exhaust', 'SRT-4. 230hp turbo Neon. Drag strip legend.', true, '5-speed Manual', false),
('Chrysler', 'Sebring', 2001, 2006, 'LX', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Chrysler', 'Sebring', 2001, 2006, 'Touring', 2, 'mid', '2.7L V6', '', 'V6 ECM, power seats', '', false, 'Automatic', false),
('Chrysler', 'Sebring', 2001, 2006, 'Limited', 3, 'premium', '2.7L V6', 'Infinity', 'Infinity amp, V6 ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Chrysler', 'Sebring', 2007, 2010, 'LX', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Chrysler', 'Sebring', 2007, 2010, 'Touring', 2, 'mid', '2.7L V6', '', 'V6 ECM, power seats', '', false, 'Automatic', false),
('Chrysler', 'Sebring', 2007, 2010, 'Limited', 3, 'premium', '3.5L V6', 'Infinity', 'Infinity amp, V6 ECM, heated leather, moonroof, nav', '', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 1997, 2003, 'SE', 1, 'base', '3.1L V6', '', '', '', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 1997, 2003, 'GT', 2, 'mid', '3.8L V6', '', 'Power seats, heated seats, monsoon stereo possible', '', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 1997, 2003, 'GTP', 3, 'premium', '3.8L Supercharged V6', '', 'Supercharged V6 ECM, sport suspension, heads-up display, 240hp', 'Supercharged 3800. Fun car.', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 2004, 2008, 'Base', 1, 'base', '3.8L V6', '', '', '', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 2004, 2008, 'GT', 2, 'mid', '3.8L V6', '', 'Power seats, heated seats, monsoon stereo', '', false, 'Automatic', false),
('Pontiac', 'Grand Prix', 2004, 2008, 'GXP', 4, 'performance', '5.3L V8', '', '5.3L V8 ECM, sport suspension, 18in wheels, 303hp', 'LS4 V8 in a sedan. Sleeper.', true, 'Automatic', false),
('Pontiac', 'Grand Am', 1999, 2005, 'SE', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Pontiac', 'Grand Am', 1999, 2005, 'GT', 2, 'mid', '3.4L V6', '', 'V6 ECM, monsoon stereo, sport suspension, 18in wheels', '', false, 'Automatic', false),
('Pontiac', 'Sunfire', 1995, 2005, 'SE', 1, 'base', '2.2L I4', '', '', 'Cavalier twin.', false, 'Automatic', false),
('Pontiac', 'Sunfire', 1995, 2005, 'GT', 2, 'mid', '2.4L I4', '', 'Sport suspension, alloy wheels, moonroof possible', '', false, 'Automatic', false),
('Chevrolet', 'Cavalier', 1995, 2005, 'Base', 1, 'base', '2.2L I4', '', '', '', false, 'Automatic', false),
('Chevrolet', 'Cavalier', 1995, 2005, 'LS', 2, 'mid', '2.2L I4', '', 'Power windows, cruise, alloy wheels', '', false, 'Automatic', false),
('Chevrolet', 'Cavalier', 1995, 2005, 'Z24', 3, 'premium', '2.4L I4', '', '2.4L ECM, sport suspension, alloy wheels, moonroof', 'Sport coupe.', false, 'Automatic', false),
('Chevrolet', 'Monte Carlo', 2000, 2007, 'LS', 1, 'base', '3.4L V6', '', '', '', false, 'Automatic', false),
('Chevrolet', 'Monte Carlo', 2000, 2007, 'LT', 2, 'mid', '3.5L V6', '', 'Power seats, heated seats possible', '', false, 'Automatic', false),
('Chevrolet', 'Monte Carlo', 2000, 2007, 'SS', 3, 'premium', '3.8L Supercharged V6', '', 'Supercharged V6 ECM, sport suspension, 240hp', 'Supercharged 3800 Series II.', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2002, 2006, 'Base', 1, 'base', '5.3L V8', '', '', 'Midgate SUV/truck.', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2002, 2006, 'Z71', 2, 'mid', '5.3L V8', '', 'Z71 suspension, skid plates', '', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2007, 2013, 'LS', 1, 'base', '5.3L V8', '', '', '', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2007, 2013, 'LT', 2, 'mid', '5.3L V8', 'Bose', 'Bose amp possible, heated seats, rear camera', '', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2007, 2013, 'LTZ', 3, 'premium', '5.3L V8', 'Bose', 'Bose amp, heated/cooled leather, nav, moonroof', '', false, 'Automatic', false),
('Chevrolet', 'Avalanche', 2007, 2013, 'Black Diamond', 2, 'mid', '5.3L V8', '', 'Special appearance pkg', '2012-2013 final edition', false, 'Automatic', false),
('Mercury', 'Mountaineer', 2002, 2005, 'Base', 2, 'mid', '4.0L V6', '', 'Power seats, leather standard', 'Explorer twin.', false, 'Automatic', false),
('Mercury', 'Mountaineer', 2002, 2005, 'Premier', 3, 'premium', '4.6L V8', 'Audiophile', 'Audiophile amp, V8 ECM, heated leather, moonroof, nav', '', false, 'Automatic', false),
('Mercury', 'Mountaineer', 2006, 2010, 'Base', 2, 'mid', '4.0L V6', '', 'Power seats, leather', '', false, 'Automatic', false),
('Mercury', 'Mountaineer', 2006, 2010, 'Premier', 3, 'premium', '4.6L V8', 'Audiophile', 'Audiophile amp, V8 ECM, heated/cooled seats, nav', '', false, 'Automatic', false),
('Mercury', 'Milan', 2006, 2011, 'Base', 1, 'base', '2.3L I4', '', '', 'Fusion twin.', false, 'Automatic', false),
('Mercury', 'Milan', 2006, 2011, 'Premier', 3, 'premium', '3.0L V6', 'Audiophile', 'Audiophile amp, V6 ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Mercury', 'Mariner', 2005, 2011, 'Base', 1, 'base', '2.3L I4', '', '', 'Escape twin.', false, 'Automatic', false),
('Mercury', 'Mariner', 2005, 2011, 'Premier', 3, 'premium', '3.0L V6', '', 'V6 ECM, heated leather, moonroof, SYNC', '', false, 'Automatic', false),
('Oldsmobile', 'Alero', 1999, 2004, 'GX', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Oldsmobile', 'Alero', 1999, 2004, 'GL', 2, 'mid', '3.4L V6', '', 'V6 ECM, power seats, monsoon stereo', '', false, 'Automatic', false),
('Oldsmobile', 'Intrigue', 1998, 2002, 'GX', 1, 'base', '3.5L V6', '', '', '', false, 'Automatic', false),
('Oldsmobile', 'Intrigue', 1998, 2002, 'GL', 2, 'mid', '3.5L V6', 'Bose', 'Bose amp, heated leather, moonroof', '', false, 'Automatic', false),
('Oldsmobile', 'Bravada', 2002, 2004, 'Base', 3, 'premium', '4.2L I6', 'Bose', 'Bose amp, heated leather, moonroof, power liftgate', 'Trailblazer twin. All premium.', false, 'Automatic', false),
('Saturn', 'Vue', 2002, 2007, 'Base', 1, 'base', '2.2L I4', '', '', '', false, 'Automatic', false),
('Saturn', 'Vue', 2002, 2007, 'V6', 2, 'mid', '3.5L V6', '', 'V6 ECM, power seats', 'Honda V6 in 2004-2007', false, 'Automatic', false),
('Saturn', 'Vue', 2008, 2010, 'XE', 1, 'base', '2.4L I4', '', '', 'GM Theta platform now.', false, 'Automatic', false),
('Saturn', 'Vue', 2008, 2010, 'XR', 3, 'premium', '3.6L V6', '', 'V6 ECM, heated leather, moonroof, 18in wheels', '', false, 'Automatic', false),
('Saturn', 'Ion', 2003, 2007, 'Base', 1, 'base', '2.2L I4', '', '', '', false, 'Automatic', false),
('Saturn', 'Ion', 2003, 2007, 'Red Line', 4, 'performance', '2.0L Supercharged I4', '', 'Supercharged ECM, sport suspension, LSD, Recaro seats', 'LSJ supercharged. Same as Cobalt SS.', true, '5-speed Manual', false),
('Saturn', 'Aura', 2007, 2009, 'XE', 1, 'base', '2.4L I4', '', '', 'Malibu twin.', false, 'Automatic', false),
('Saturn', 'Aura', 2007, 2009, 'XR', 3, 'premium', '3.6L V6', '', 'V6 ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Saturn', 'Outlook', 2007, 2010, 'XE', 1, 'base', '3.6L V6', '', '', 'Acadia/Traverse twin.', false, 'Automatic', false),
('Saturn', 'Outlook', 2007, 2010, 'XR', 3, 'premium', '3.6L V6', '', 'Heated leather, moonroof, rear entertainment, power liftgate', '', false, 'Automatic', false),
('Saturn', 'Sky', 2007, 2010, 'Base', 2, 'mid', '2.4L I4', '', 'Power seats, OnStar', 'Solstice twin.', true, 'Automatic', false),
('Saturn', 'Sky', 2007, 2010, 'Red Line', 4, 'performance', '2.0L Turbo I4', '', 'Turbo ECM, sport suspension, LSD, Brembo possible, 260hp', 'Turbo roadster. Same as Solstice GXP.', true, '5-speed Manual', false),
('Pontiac', 'Solstice', 2006, 2009, 'Base', 2, 'mid', '2.4L I4', '', 'Power seats, OnStar', 'GM roadster.', true, '5-speed Manual', false),
('Pontiac', 'Solstice', 2006, 2009, 'GXP', 4, 'performance', '2.0L Turbo I4 (260hp)', '', 'Turbo ECM, LSD, sport suspension, Brembo brakes possible', 'Turbo Solstice. Same engine as Sky Red Line.', true, '5-speed Manual', false),
('Pontiac', 'GTO', 2004, 2006, 'Base', 3, 'premium', '5.7L V8 (LS1)', '', 'LS1 ECM (2004), LS2 ECM (2005-06), 6-speed manual, sport suspension, Brembo possible', 'Holden Monaro import. LS1 2004, LS2 2005-06. 400hp.', true, '6-speed Manual', false),
('Pontiac', 'Vibe', 2003, 2008, 'Base', 1, 'base', '1.8L I4', '', '', 'Matrix twin.', false, 'Automatic', false),
('Pontiac', 'Vibe', 2003, 2008, 'GT', 3, 'premium', '1.8L I4 (170hp) 2ZZ-GE', '', '2ZZ-GE ECM, 6-speed manual, sport suspension, 8200rpm', '2ZZ-GE high-rev engine. Same as Matrix XRS.', true, '6-speed Manual', false),
('Pontiac', 'Vibe', 2009, 2010, 'Base', 1, 'base', '1.8L I4', '', '', '', false, 'Automatic', false),
('Pontiac', 'Vibe', 2009, 2010, 'GT', 2, 'mid', '2.4L I4', '', '2.4L ECM, sport appearance', 'No more 2ZZ.', false, 'Automatic', false),
('Scion', 'xB', 2004, 2006, 'Base', 1, 'base', '1.5L I4 (1NZ-FE)', '', '', 'Toaster. One trim.', true, '4-speed Automatic', false),
('Scion', 'xB', 2008, 2015, 'Base', 1, 'base', '2.4L I4 (2AZ-FE)', '', '', 'Bigger xB. One trim.', false, '4-speed Automatic', false),
('Scion', 'tC', 2005, 2010, 'Base', 2, 'mid', '2.4L I4 (2AZ-FE)', '', 'Moonroof, power seats standard', 'Sporty coupe. One trim level.', false, '5-speed Manual', false),
('Scion', 'tC', 2011, 2016, 'Base', 2, 'mid', '2.5L I4 (2AR-FE)', '', 'Moonroof, power seats standard', '', false, '6-speed Manual', false),
('Scion', 'FR-S', 2013, 2016, 'Base', 3, 'premium', '2.0L H4 (FA20)', '', 'FA20 ECM, LSD, sport suspension', 'BRZ/86 twin. All are cult.', true, '6-speed Manual', false),
('Toyota', 'Echo', 2000, 2005, 'Base', 1, 'base', '1.5L I4 (1NZ-FE)', '', '', '', false, 'Automatic', false),
('Toyota', 'Yaris', 2006, 2018, 'Base', 1, 'base', '1.5L I4', '', '', '', false, 'Automatic', false),
('Toyota', 'Venza', 2009, 2015, 'Base', 1, 'base', '2.7L I4', '', '', '', false, 'Automatic', false),
('Toyota', 'Venza', 2009, 2015, 'XLE', 3, 'premium', '3.5L V6', 'JBL', 'JBL amp, V6 ECM, heated leather, moonroof, nav, rear camera', '', false, 'Automatic', false),
('Toyota', 'Sequoia', 2001, 2007, 'SR5', 2, 'mid', '4.7L V8 (2UZ-FE)', '', '2UZ-FE V8 ECM, power seats, rear A/C', '2UZ-FE bulletproof V8.', true, 'Automatic', false),
('Toyota', 'Sequoia', 2001, 2007, 'Limited', 3, 'premium', '4.7L V8 (2UZ-FE)', 'JBL', 'JBL amp, 2UZ-FE V8 ECM, heated leather, moonroof, nav, rear entertainment', '', true, 'Automatic', false),
('Toyota', 'Sequoia', 2008, 2022, 'SR5', 2, 'mid', '5.7L V8', '', 'V8 ECM, power seats, rear camera', '', false, 'Automatic', false),
('Toyota', 'Sequoia', 2008, 2022, 'Limited', 3, 'premium', '5.7L V8', 'JBL', 'JBL amp, V8 ECM, heated/ventilated leather, nav, rear entertainment', '', false, 'Automatic', false),
('Toyota', 'Sequoia', 2008, 2022, 'Platinum', 3, 'premium', '5.7L V8', 'JBL', 'JBL amp, V8 ECM, heated/ventilated leather, nav, rear entertainment, power folding 3rd row', '', false, 'Automatic', false),
('Toyota', 'Sequoia', 2008, 2022, 'TRD Pro', 4, 'performance', '5.7L V8', 'JBL', 'JBL amp, V8 ECM, Fox shocks, TRD skid plate, TRD exhaust', '2020+. Off-road Sequoia.', true, 'Automatic', false),
('Honda', 'HR-V', 2016, 2022, 'LX', 1, 'base', '1.8L I4', '', '', '', false, 'CVT', false),
('Honda', 'HR-V', 2016, 2022, 'EX', 2, 'mid', '1.8L I4', '', 'Honda Sensing, moonroof, heated seats', '', false, 'CVT', false),
('Honda', 'HR-V', 2016, 2022, 'EX-L', 3, 'premium', '1.8L I4', '', 'Heated leather, moonroof, Honda Sensing', '', false, 'CVT', false),
('Hyundai', 'Santa Cruz', 2022, 2025, 'SE', 1, 'base', '2.5L I4', '', '', 'Sport truck. Tucson platform.', false, 'Automatic', false),
('Hyundai', 'Santa Cruz', 2022, 2025, 'SEL', 2, 'mid', '2.5L I4', '', 'Heated seats, blind spot, rear camera', '', false, 'Automatic', false),
('Hyundai', 'Santa Cruz', 2022, 2025, 'Limited', 3, 'premium', '2.5L Turbo', 'Bose', 'Bose amp, turbo ECM, heated/ventilated leather, nav, 360 camera', '', false, 'Automatic', false),
('Kia', 'Sedona', 2002, 2005, 'LX', 1, 'base', '3.5L V6', '', '', '', false, 'Automatic', false),
('Kia', 'Sedona', 2002, 2005, 'EX', 3, 'premium', '3.5L V6', 'Infinity', 'Infinity amp, heated leather, rear entertainment', '', false, 'Automatic', false),
('Kia', 'Sedona', 2006, 2014, 'LX', 1, 'base', '3.8L V6', '', '', '', false, 'Automatic', false),
('Kia', 'Sedona', 2006, 2014, 'EX', 3, 'premium', '3.8L V6', 'Infinity', 'Infinity amp, heated leather, moonroof, rear entertainment', '', false, 'Automatic', false),
('Kia', 'Sedona', 2015, 2021, 'LX', 1, 'base', '3.3L V6', '', '', '', false, 'Automatic', false),
('Kia', 'Sedona', 2015, 2021, 'EX', 2, 'mid', '3.3L V6', '', 'Power sliding doors, heated seats, rear camera', '', false, 'Automatic', false),
('Kia', 'Sedona', 2015, 2021, 'SX', 3, 'premium', '3.3L V6', 'Infinity', 'Infinity amp, heated/ventilated leather, moonroof, nav, rear entertainment, power liftgate', '', false, 'Automatic', false),
('Hyundai', 'Kona', 2018, 2025, 'SE', 1, 'base', '2.0L I4', '', '', '', false, 'Automatic', false),
('Hyundai', 'Kona', 2018, 2025, 'SEL', 2, 'mid', '2.0L I4', '', 'Heated seats, blind spot, rear camera', '', false, 'Automatic', false),
('Hyundai', 'Kona', 2018, 2025, 'Limited', 3, 'premium', '1.6L Turbo', '', 'Turbo ECM, heated/ventilated leather, heads-up display', '', false, 'Automatic', false),
('Hyundai', 'Kona', 2018, 2025, 'N', 4, 'performance', '2.0L Turbo (276hp)', '', 'N ECM, electronic LSD, adaptive suspension, N drive modes, launch control', '2022+. Hot crossover.', true, 'Automatic', false),
('Ford', 'Flex', 2009, 2019, 'SE', 1, 'base', '3.5L V6', '', '', '', false, 'Automatic', false),
('Ford', 'Flex', 2009, 2019, 'SEL', 2, 'mid', '3.5L V6', '', 'SYNC, power liftgate, rear camera', '', false, 'Automatic', false),
('Ford', 'Flex', 2009, 2019, 'Limited', 3, 'premium', '3.5L V6', 'Sony', 'Sony amp, heated/cooled leather, nav, park assist, adaptive cruise', '', false, 'Automatic', false),
('Ford', 'Flex', 2009, 2019, 'Limited EcoBoost', 3, 'premium', '3.5L EcoBoost', 'Sony', 'Sony amp, EcoBoost ECM, heated/cooled leather, nav, 355hp', 'Twin-turbo Flex. Sleeper.', false, 'Automatic', false),
('Ford', 'Freestyle', 2005, 2007, 'SE', 1, 'base', '3.0L V6', '', '', 'Pre-Flex. CVT.', false, 'CVT', false),
('Ford', 'Freestyle', 2005, 2007, 'Limited', 3, 'premium', '3.0L V6', 'Audiophile', 'Audiophile amp, heated leather, nav', '', false, 'CVT', false),
('Ford', 'Taurus X', 2008, 2009, 'SEL', 2, 'mid', '3.5L V6', '', 'Power seats, SYNC, rear camera', '', false, 'Automatic', false),
('Ford', 'Taurus X', 2008, 2009, 'Limited', 3, 'premium', '3.5L V6', 'Audiophile', 'Audiophile amp, heated leather, nav', '', false, 'Automatic', false),
('Ford', 'Windstar', 1999, 2003, 'LX', 1, 'base', '3.8L V6', '', '', '', false, 'Automatic', false),
('Ford', 'Windstar', 1999, 2003, 'SEL', 3, 'premium', '3.8L V6', 'Audiophile', 'Audiophile amp, heated leather, rear entertainment', '', false, 'Automatic', false),
('Ford', 'Freestar', 2004, 2007, 'S', 1, 'base', '3.9L V6', '', '', '', false, 'Automatic', false),
('Ford', 'Freestar', 2004, 2007, 'Limited', 3, 'premium', '4.2L V6', 'Audiophile', 'Audiophile amp, heated leather, rear entertainment, power sliding doors', '', false, 'Automatic', false),
('Chevrolet', 'Venture', 1997, 2005, 'Base', 1, 'base', '3.4L V6', '', '', '', false, 'Automatic', false),
('Chevrolet', 'Venture', 1997, 2005, 'LT', 2, 'mid', '3.4L V6', '', 'Power sliding doors, rear entertainment possible', '', false, 'Automatic', false),
('Chevrolet', 'Uplander', 2005, 2009, 'LS', 1, 'base', '3.5L V6', '', '', '', false, 'Automatic', false),
('Chevrolet', 'Uplander', 2005, 2009, 'LT', 2, 'mid', '3.9L V6', '', 'Power sliding doors, heated seats, rear entertainment possible', '', false, 'Automatic', false),
('Pontiac', 'Montana', 1999, 2005, 'Base', 1, 'base', '3.4L V6', '', '', 'Venture twin.', false, 'Automatic', false),
('Jeep', 'Compass', 2007, 2017, 'Sport', 1, 'base', '2.0L I4', '', '', '', false, 'CVT', false),
('Jeep', 'Compass', 2007, 2017, 'Latitude', 2, 'mid', '2.4L I4', '', 'Heated seats, rear camera, Uconnect', '', false, 'Automatic', false),
('Jeep', 'Compass', 2007, 2017, 'Limited', 3, 'premium', '2.4L I4', '', 'Heated leather, moonroof, nav, power seats', '', false, 'Automatic', false),
('Jeep', 'Compass', 2017, 2025, 'Sport', 1, 'base', '2.4L I4', '', '', 'New platform.', false, 'Automatic', false),
('Jeep', 'Compass', 2017, 2025, 'Latitude', 2, 'mid', '2.4L I4', '', 'Heated seats, Uconnect, rear camera', '', false, 'Automatic', false),
('Jeep', 'Compass', 2017, 2025, 'Limited', 3, 'premium', '2.4L I4', 'Alpine', 'Alpine amp, heated leather, nav, park assist', '', false, 'Automatic', false),
('Jeep', 'Compass', 2017, 2025, 'Trailhawk', 2, 'mid', '2.4L I4', '', 'Off-road suspension, skid plates, 4WD Lock', '', false, 'Automatic', false),
('Jeep', 'Patriot', 2007, 2017, 'Sport', 1, 'base', '2.0L I4', '', '', '', false, '5-speed Manual', false),
('Jeep', 'Patriot', 2007, 2017, 'Latitude', 2, 'mid', '2.4L I4', '', 'Heated seats, rear camera', '', false, 'Automatic', false),
('Jeep', 'Patriot', 2007, 2017, 'Limited', 3, 'premium', '2.4L I4', '', 'Heated leather, moonroof, nav, power seats', '', false, 'Automatic', false),
('Jeep', 'Renegade', 2015, 2023, 'Sport', 1, 'base', '2.4L I4', '', '', 'Fiat 500X platform.', false, 'Automatic', false),
('Jeep', 'Renegade', 2015, 2023, 'Latitude', 2, 'mid', '2.4L I4', '', 'Heated seats, Uconnect, rear camera', '', false, 'Automatic', false),
('Jeep', 'Renegade', 2015, 2023, 'Limited', 3, 'premium', '2.4L I4', 'Beats', 'Beats amp, heated leather, nav, moonroof', '', false, 'Automatic', false),
('Jeep', 'Renegade', 2015, 2023, 'Trailhawk', 2, 'mid', '2.4L I4', '', 'Off-road suspension, skid plates, Selec-Terrain', '', false, 'Automatic', false);

-- Total: 135 entries
