INSERT INTO trim_tier_reference (make, model, gen_start, gen_end, trim, tier, tier_name, top_engine, audio_brand, expected_parts, notes, cult, transmission, diesel) VALUES
('Lexus', 'ES300', 1997, 2001, 'Base', 2, 'mid', '3.0L V6', '', 'Power seats, heated seats, leather, moonroof, auto climate', 'XV20. 1MZ-FE V6. Only one trim.', false, 'Automatic', false),
('Lexus', 'ES300', 2002, 2003, 'Base', 2, 'mid', '3.0L V6', '', 'Power seats, heated seats, leather, moonroof, auto climate', 'XV30. All ES are premium.', false, 'Automatic', false),
('Lexus', 'ES330', 2004, 2006, 'Base', 2, 'mid', '3.3L V6', '', 'Power seats, heated seats, leather, moonroof, auto climate', '3MZ-FE V6.', false, 'Automatic', false),
('Lexus', 'ES350', 2007, 2012, 'Base', 2, 'mid', '3.5L V6', 'Mark Levinson', 'Mark Levinson amp possible, heated/ventilated seats, nav possible, moonroof', '2GR-FE V6.', false, 'Automatic', false),
('Lexus', 'ES350', 2013, 2018, 'Base', 2, 'mid', '3.5L V6', 'Mark Levinson', 'Mark Levinson amp possible, heated/ventilated seats, nav, blind spot, moonroof', '', false, 'Automatic', false),
('Lexus', 'RX300', 1999, 2003, 'Base', 2, 'mid', '3.0L V6', '', 'Power seats, heated seats, leather, moonroof', '1MZ-FE V6. 1st gen RX.', false, 'Automatic', false),
('Lexus', 'NX', 2015, 2021, 'NX 200t', 2, 'mid', '2.0L Turbo', '', 'Power liftgate, heated seats, Lexus Safety', '', false, 'Automatic', false),
('Lexus', 'NX', 2015, 2021, 'NX 300', 2, 'mid', '2.0L Turbo', '', 'Power liftgate, heated seats, Lexus Safety', 'Renamed from 200t in 2018', false, 'Automatic', false),
('Lexus', 'NX', 2015, 2021, 'NX 300 F Sport', 3, 'premium', '2.0L Turbo', 'Mark Levinson', 'Mark Levinson amp, adaptive suspension, sport seats, nav, heads-up display', '', false, 'Automatic', false),
('Lexus', 'LS', 2001, 2006, 'LS 430', 3, 'premium', '4.3L V8', 'Mark Levinson', 'Mark Levinson amp, V8 ECM, air suspension, heated/ventilated seats, nav, adaptive cruise', 'Flagship Lexus. 3UZ-FE V8.', false, 'Automatic', false),
('Lexus', 'LS', 2007, 2017, 'LS 460', 3, 'premium', '4.6L V8', 'Mark Levinson', 'Mark Levinson amp, V8 ECM, air suspension, heated/ventilated seats, nav, adaptive cruise, 360 camera', '1UR-FSE V8.', false, 'Automatic', false),
('Lexus', 'SC', 2002, 2010, 'SC 430', 3, 'premium', '4.3L V8', 'Mark Levinson', 'Mark Levinson amp, V8 ECM, nav, heated/ventilated seats, power hardtop', 'Retractable hardtop coupe. 3UZ-FE V8.', false, 'Automatic', false),
('Infiniti', 'M35', 2006, 2010, 'Base', 2, 'mid', '3.5L V6', 'Bose', 'Bose amp, VQ35 ECM, heated seats, nav, moonroof', 'VQ35HR V6.', false, 'Automatic', false),
('Infiniti', 'M35', 2006, 2010, 'Sport', 3, 'premium', '3.5L V6', 'Bose', 'Bose amp, VQ35 ECM, sport suspension, sport brakes, nav, heated/cooled seats', '', false, 'Automatic', false),
('Infiniti', 'M45', 2003, 2010, 'Base', 3, 'premium', '4.5L V8', 'Bose', 'Bose amp, VK45 V8 ECM, heated/cooled seats, nav, adaptive cruise', 'VK45DE V8.', false, 'Automatic', false),
('Infiniti', 'FX35', 2003, 2008, 'Base', 3, 'premium', '3.5L V6', 'Bose', 'Bose amp, VQ35 ECM, heated leather, nav, moonroof, rear camera', 'Sport crossover.', false, 'Automatic', false),
('Infiniti', 'FX45', 2003, 2008, 'Base', 3, 'premium', '4.5L V8', 'Bose', 'Bose amp, VK45 V8 ECM, heated/cooled leather, nav, adaptive cruise', '', false, 'Automatic', false),
('Infiniti', 'FX35', 2009, 2013, 'Base', 3, 'premium', '3.5L V6', 'Bose', 'Bose amp, VQ35 ECM, heated leather, nav, 360 camera', '', false, 'Automatic', false),
('Infiniti', 'FX50', 2009, 2013, 'Base', 3, 'premium', '5.0L V8', 'Bose', 'Bose amp, VK50 V8 ECM, heated/cooled leather, nav, adaptive cruise, 360 camera', 'VK50VE V8. 390hp.', false, 'Automatic', false),
('Infiniti', 'QX60', 2014, 2020, 'Base', 2, 'mid', '3.5L V6', 'Bose', 'Bose amp, VQ35 ECM, heated leather, rear camera', '', false, 'CVT', false),
('Infiniti', 'QX60', 2014, 2020, 'Luxe', 3, 'premium', '3.5L V6', 'Bose', 'Bose amp, heated/cooled leather, nav, 360 camera, adaptive cruise', '', false, 'CVT', false),
('Infiniti', 'QX80', 2014, 2025, 'Base', 3, 'premium', '5.6L V8', 'Bose', 'Bose amp, VK56 V8 ECM, heated/cooled leather, nav, rear entertainment, 360 camera, adaptive cruise', 'Armada luxury twin.', false, 'Automatic', false),
('Audi', 'A3', 2006, 2013, '2.0T', 2, 'mid', '2.0L Turbo I4', '', 'Power seats, heated seats, moonroof', 'EA113/EA888 turbo.', false, 'Automatic', false),
('Audi', 'A3', 2006, 2013, '2.0T Premium', 3, 'premium', '2.0L Turbo I4', 'Bose', 'Bose amp, heated leather, nav, moonroof', '', false, 'Automatic', false),
('Audi', 'A3', 2006, 2013, 'S3', 4, 'performance', '2.0L Turbo I4 (292hp)', '', 'S3 ECM, magnetic ride, sport differential, sport suspension', '2015+ only.', true, 'Automatic', false),
('Audi', 'A3', 2015, 2025, 'Premium', 2, 'mid', '2.0L Turbo I4', '', 'Virtual Cockpit possible, heated seats', '', false, 'Automatic', false),
('Audi', 'A3', 2015, 2025, 'Premium Plus', 3, 'premium', '2.0L Turbo I4', 'Bang & Olufsen', 'B&O amp, Virtual Cockpit, nav, blind spot, parking sensors', '', false, 'Automatic', false),
('Audi', 'A3', 2015, 2025, 'S3', 4, 'performance', '2.0L Turbo I4 (306hp)', 'Bang & Olufsen', 'B&O amp, S3 ECM, magnetic ride, sport differential, sport exhaust', '', true, 'Automatic', false),
('Audi', 'A3', 2015, 2025, 'RS3', 4, 'performance', '2.5L Turbo I5 (401hp)', 'Bang & Olufsen', 'B&O amp, 2.5L I5 ECM, sport differential, magnetic ride, ceramic brakes possible, 401hp', '5-cylinder turbo. Same as TT RS.', true, 'Automatic', false),
('Audi', 'Q3', 2015, 2018, 'Premium', 2, 'mid', '2.0L Turbo I4', '', 'Heated seats, panoramic moonroof', '', false, 'Automatic', false),
('Audi', 'Q3', 2015, 2018, 'Premium Plus', 3, 'premium', '2.0L Turbo I4', 'Bose', 'Bose amp, heated leather, nav, parking sensors', '', false, 'Automatic', false),
('Audi', 'Q3', 2019, 2025, 'Premium', 2, 'mid', '2.0L Turbo I4', '', 'Virtual Cockpit, heated seats', '', false, 'Automatic', false),
('Audi', 'Q3', 2019, 2025, 'Premium Plus', 3, 'premium', '2.0L Turbo I4', 'Bang & Olufsen', 'B&O amp, Virtual Cockpit, nav, 360 camera, wireless charging', '', false, 'Automatic', false),
('BMW', 'X3', 2004, 2010, 'xDrive30i', 2, 'mid', '3.0L I6', '', 'Panoramic moonroof, power seats, iDrive', 'E83. N52 engine.', false, 'Automatic', false),
('BMW', 'X3', 2011, 2017, 'xDrive28i', 2, 'mid', '2.0L Turbo I4', '', 'Panoramic moonroof, power seats, iDrive', 'F25. N20 engine.', false, 'Automatic', false),
('BMW', 'X3', 2011, 2017, 'xDrive35i', 3, 'premium', '3.0L Turbo I6', 'Harman Kardon', 'Harman Kardon amp, N55 ECM, sport seats, nav', '', false, 'Automatic', false),
('BMW', 'X3', 2011, 2017, 'X3 M', 4, 'performance', '3.0L Turbo I6', 'Harman Kardon', 'Harman Kardon amp, S55 ECM, M differential, adaptive M suspension', '2015+. M Sport pkg.', false, 'Automatic', false),
('BMW', 'X3', 2018, 2025, 'xDrive30i', 2, 'mid', '2.0L Turbo I4', '', 'Live Cockpit, panoramic moonroof', 'G01.', false, 'Automatic', false),
('BMW', 'X3', 2018, 2025, 'M40i', 3, 'premium', '3.0L Turbo I6', 'Harman Kardon', 'Harman Kardon amp, B58 ECM, M Sport differential, adaptive suspension', '', false, 'Automatic', false),
('BMW', 'X3', 2018, 2025, 'X3 M', 4, 'performance', '3.0L Twin-Turbo I6', 'Harman Kardon', 'Harman Kardon amp, S58 ECM, M differential, adaptive M suspension, M brakes', '473-503hp', true, 'Automatic', false),
('Mercedes-Benz', 'C-Class', 2012, 2015, 'C250', 2, 'mid', '1.8L Turbo I4', '', 'Power seats, COMAND possible', 'M271 turbo. Base C-Class.', false, 'Automatic', false),
('Mercedes-Benz', 'GLC', 2016, 2025, 'GLC300', 2, 'mid', '2.0L Turbo', '', 'MBUX, power seats, heated seats', '', false, 'Automatic', false),
('Mercedes-Benz', 'GLC', 2016, 2025, 'GLC43 AMG', 3, 'premium', '3.0L Twin-Turbo V6', 'Burmester', 'Burmester amp, AMG ECM, AMG suspension, AMG brakes', '', false, 'Automatic', false),
('Mercedes-Benz', 'GLC', 2016, 2025, 'GLC63 AMG', 4, 'performance', '4.0L Twin-Turbo V8', 'Burmester', 'Burmester amp, M177 V8 ECM, AMG suspension, AMG brakes, electronic LSD', '503hp', false, 'Automatic', false),
('Mercedes-Benz', 'CLA', 2014, 2019, 'CLA250', 2, 'mid', '2.0L Turbo', '', 'Power seats, COMAND, heated seats', '', false, 'Automatic', false),
('Mercedes-Benz', 'CLA', 2014, 2019, 'CLA45 AMG', 4, 'performance', '2.0L Turbo I4 (375hp)', 'Harman Kardon', 'Harman Kardon amp, AMG ECM, AMG suspension, Recaro possible, 375hp', 'Fastest turbo 4-cyl AMG.', true, 'Automatic', false),
('Mercedes-Benz', 'CLA', 2020, 2025, 'CLA250', 2, 'mid', '2.0L Turbo', '', 'MBUX, power seats', '', false, 'Automatic', false),
('Mercedes-Benz', 'CLA', 2020, 2025, 'CLA35 AMG', 3, 'premium', '2.0L Turbo (302hp)', 'Burmester', 'Burmester amp, AMG ECM, AMG suspension', '', false, 'Automatic', false),
('Mercedes-Benz', 'GLA', 2015, 2019, 'GLA250', 2, 'mid', '2.0L Turbo', '', 'Power seats, COMAND', '', false, 'Automatic', false),
('Mercedes-Benz', 'GLA', 2015, 2019, 'GLA45 AMG', 4, 'performance', '2.0L Turbo I4 (375hp)', 'Harman Kardon', 'Harman Kardon amp, AMG ECM, AMG suspension, 375hp', '', true, 'Automatic', false),
('Mercedes-Benz', 'GLK', 2010, 2015, 'GLK350', 2, 'mid', '3.5L V6', '', 'Power seats, heated seats, COMAND possible', '', false, 'Automatic', false),
('Mercedes-Benz', 'S-Class', 2000, 2006, 'S430', 3, 'premium', '4.3L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated/cooled seats, nav, Distronic', 'W220.', false, 'Automatic', false),
('Mercedes-Benz', 'S-Class', 2000, 2006, 'S500', 3, 'premium', '5.0L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated/cooled seats, nav, Distronic', '', false, 'Automatic', false),
('Mercedes-Benz', 'S-Class', 2000, 2006, 'S55 AMG', 4, 'performance', '5.4L Supercharged V8', 'Harman Kardon', 'Harman Kardon amp, supercharged V8 ECM, air suspension, AMG brakes', '493hp supercharged.', true, 'Automatic', false),
('Mercedes-Benz', 'S-Class', 2007, 2013, 'S550', 3, 'premium', '5.5L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated/cooled seats, nav, Distronic, night vision', 'W221.', false, 'Automatic', false),
('Mercedes-Benz', 'S-Class', 2007, 2013, 'S63 AMG', 4, 'performance', '5.5L Twin-Turbo V8', 'Harman Kardon', 'Harman Kardon amp, M157 V8 ECM, AMG suspension, AMG brakes', '536hp twin-turbo.', false, 'Automatic', false),
('Mercedes-Benz', 'G-Class', 2002, 2018, 'G500', 3, 'premium', '5.0L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, locking diffs (3), heated leather, nav', 'If a G-Wagon shows up at LKQ, pull everything.', true, 'Automatic', false),
('Mercedes-Benz', 'G-Class', 2002, 2018, 'G55 AMG', 4, 'performance', '5.4L Supercharged V8', 'Harman Kardon', 'Harman Kardon amp, supercharged V8 ECM, locking diffs, AMG brakes, AMG suspension', '493hp supercharged G-Wagon.', true, 'Automatic', false),
('Mercedes-Benz', 'G-Class', 2019, 2025, 'G550', 3, 'premium', '4.0L Twin-Turbo V8', 'Burmester', 'Burmester amp, V8 ECM, locking diffs (3), adaptive suspension, heated/cooled seats', '', true, 'Automatic', false),
('Mercedes-Benz', 'G-Class', 2019, 2025, 'G63 AMG', 4, 'performance', '4.0L Twin-Turbo V8 (577hp)', 'Burmester', 'Burmester amp, M177 V8 ECM, locking diffs, AMG suspension, 577hp', '', true, 'Automatic', false),
('Lincoln', 'Aviator', 2003, 2005, 'Base', 3, 'premium', '4.6L V8', 'THX', 'THX amp, V8 ECM, air suspension, heated/cooled leather, nav', 'Explorer platform V8 luxury.', false, 'Automatic', false),
('Lincoln', 'Aviator', 2020, 2025, 'Standard', 3, 'premium', '3.0L Twin-Turbo V6', 'Revel', 'Revel amp, twin-turbo ECM, air suspension, heated/cooled seats, SYNC 3', '400hp twin-turbo.', false, 'Automatic', false),
('Lincoln', 'Aviator', 2020, 2025, 'Reserve', 3, 'premium', '3.0L Twin-Turbo V6', 'Revel', 'Revel amp, twin-turbo ECM, air suspension, heated/cooled/massage seats, adaptive cruise, 360 camera', '', false, 'Automatic', false),
('Lincoln', 'Aviator', 2020, 2025, 'Black Label', 3, 'premium', '3.0L Twin-Turbo V6', 'Revel Ultima', 'Revel Ultima amp, twin-turbo ECM, air suspension, premium everything', '', false, 'Automatic', false),
('Lincoln', 'MKC', 2015, 2019, 'Premiere', 2, 'mid', '2.0L Turbo', '', 'SYNC, heated seats, power liftgate', '', false, 'Automatic', false),
('Lincoln', 'MKC', 2015, 2019, 'Reserve', 3, 'premium', '2.3L Turbo', 'THX', 'THX amp, heated/cooled seats, nav, park assist, adaptive cruise', '', false, 'Automatic', false),
('Lincoln', 'Corsair', 2020, 2025, 'Standard', 2, 'mid', '2.0L Turbo', '', 'SYNC 3, heated seats, power liftgate', '', false, 'Automatic', false),
('Lincoln', 'Corsair', 2020, 2025, 'Reserve', 3, 'premium', '2.3L Turbo', 'Revel', 'Revel amp, heated/cooled seats, adaptive cruise, 360 camera', '', false, 'Automatic', false),
('Lincoln', 'Nautilus', 2019, 2025, 'Standard', 2, 'mid', '2.0L Turbo', '', 'SYNC 3, heated seats, power liftgate', '', false, 'Automatic', false),
('Lincoln', 'Nautilus', 2019, 2025, 'Reserve', 3, 'premium', '2.7L EcoBoost', 'Revel', 'Revel amp, heated/cooled seats, adaptive cruise, 360 camera, heads-up display', '', false, 'Automatic', false),
('Lincoln', 'Continental', 2017, 2020, 'Premiere', 2, 'mid', '3.7L V6', '', 'Power seats, SYNC 3, heated seats', '', false, 'Automatic', false),
('Lincoln', 'Continental', 2017, 2020, 'Reserve', 3, 'premium', '2.7L Twin-Turbo V6', 'Revel', 'Revel amp, twin-turbo ECM, heated/cooled seats, adaptive cruise, 360 camera', '', false, 'Automatic', false),
('Lincoln', 'Continental', 2017, 2020, 'Black Label', 3, 'premium', '3.0L Twin-Turbo V6', 'Revel Ultima', 'Revel Ultima 19-speaker amp, twin-turbo ECM, heated/cooled/massage seats, Alcantara headliner', '400hp.', false, 'Automatic', false),
('Cadillac', 'XT5', 2017, 2025, 'Luxury', 2, 'mid', '3.6L V6', 'Bose', 'Bose amp, heated leather, CUE, rear camera', '', false, 'Automatic', false),
('Cadillac', 'XT5', 2017, 2025, 'Premium Luxury', 3, 'premium', '3.6L V6', 'Bose', 'Bose amp, heated/cooled leather, nav, adaptive cruise, 360 camera, heads-up display', '', false, 'Automatic', false),
('Cadillac', 'XT4', 2019, 2025, 'Luxury', 2, 'mid', '2.0L Turbo', 'Bose', 'Bose amp, turbo ECM, heated leather, CUE', '', false, 'Automatic', false),
('Cadillac', 'XT4', 2019, 2025, 'Premium Luxury', 3, 'premium', '2.0L Turbo', 'Bose', 'Bose amp, turbo ECM, heated/cooled leather, nav, adaptive cruise, 360 camera', '', false, 'Automatic', false),
('Cadillac', 'XT4', 2019, 2025, 'Sport', 2, 'mid', '2.0L Turbo', 'Bose', 'Bose amp, sport appearance, sport suspension', '', false, 'Automatic', false),
('Cadillac', 'CT5', 2020, 2025, 'Luxury', 2, 'mid', '2.0L Turbo', 'Bose', 'Bose amp, heated leather, CUE', '', false, 'Automatic', false),
('Cadillac', 'CT5', 2020, 2025, 'Premium Luxury', 3, 'premium', '2.0L Turbo', 'Bose', 'Bose amp, heated/cooled leather, heads-up display, adaptive cruise', '', false, 'Automatic', false),
('Cadillac', 'CT5', 2020, 2025, 'CT5-V', 3, 'premium', '3.0L Twin-Turbo V6', 'Bose', 'Bose amp, twin-turbo ECM, magnetic ride, sport brakes, electronic LSD', '360hp.', false, 'Automatic', false),
('Cadillac', 'CT5', 2020, 2025, 'CT5-V Blackwing', 4, 'performance', '6.2L Supercharged V8 (LT4) 668hp', 'Bose', 'Bose amp, LT4 supercharged ECM, magnetic ride, Brembo carbon ceramics, 6-speed manual, electronic LSD', 'Last V8 manual Cadillac. 668hp. Instant cult classic.', true, '6-speed Manual', false),
('Cadillac', 'ATS', 2013, 2019, 'Base', 2, 'mid', '2.5L I4', 'Bose', 'Bose amp, CUE, heated leather', '', false, 'Automatic', false),
('Cadillac', 'ATS', 2013, 2019, 'Premium', 3, 'premium', '3.6L V6', 'Bose', 'Bose amp, V6 ECM, heated/cooled leather, nav, magnetic ride', '', false, 'Automatic', false),
('Cadillac', 'ATS', 2013, 2019, 'ATS-V', 4, 'performance', '3.6L Twin-Turbo V6 (464hp)', 'Bose', 'Bose amp, twin-turbo ECM, magnetic ride, Brembo brakes, electronic LSD, 6-speed manual', 'Baby CTS-V. 464hp.', true, '6-speed Manual', false),
('Cadillac', 'DeVille', 1997, 2005, 'Base', 2, 'mid', '4.6L V8', 'Bose', 'Bose amp, Northstar V8 ECM, heated leather', 'Northstar V8.', false, 'Automatic', false),
('Cadillac', 'DeVille', 1997, 2005, 'DTS', 3, 'premium', '4.6L V8 (300hp)', 'Bose', 'Bose amp, Northstar V8 ECM (DTS tune), heated/cooled leather, nav, magnetic ride', '', false, 'Automatic', false),
('Cadillac', 'DTS', 2006, 2011, 'Base', 2, 'mid', '4.6L V8', 'Bose', 'Bose amp, Northstar V8 ECM, heated leather', '', false, 'Automatic', false),
('Cadillac', 'DTS', 2006, 2011, 'Platinum', 3, 'premium', '4.6L V8 (292hp)', 'Bose', 'Bose amp, Northstar V8 ECM, heated/cooled leather, nav, magnetic ride, adaptive cruise', '', false, 'Automatic', false),
('Jaguar', 'XF', 2009, 2015, 'Base', 2, 'mid', '3.0L V6', '', 'Power seats, heated leather, nav', '', false, 'Automatic', false),
('Jaguar', 'XF', 2009, 2015, 'Premium', 3, 'premium', '3.0L Supercharged V6', '', 'Supercharged V6 ECM, heated/cooled leather, nav, adaptive suspension', '', false, 'Automatic', false),
('Jaguar', 'XF', 2009, 2015, 'XFR', 4, 'performance', '5.0L Supercharged V8', '', 'Supercharged V8 ECM, adaptive suspension, Brembo brakes, 510hp', '', true, 'Automatic', false),
('Jaguar', 'XF', 2016, 2025, '25t', 2, 'mid', '2.0L Turbo I4', '', 'Heated leather, InControl, blind spot', 'X260.', false, 'Automatic', false),
('Jaguar', 'XF', 2016, 2025, 'S', 3, 'premium', '3.0L Supercharged V6', '', 'Supercharged V6 ECM, adaptive suspension, heated/cooled leather, nav', '', false, 'Automatic', false),
('Jaguar', 'F-Pace', 2017, 2025, '25t', 2, 'mid', '2.0L Turbo I4', '', 'Heated leather, InControl', '', false, 'Automatic', false),
('Jaguar', 'F-Pace', 2017, 2025, 'S', 3, 'premium', '3.0L Supercharged V6', '', 'Supercharged V6 ECM, adaptive suspension, heated/cooled leather', '', false, 'Automatic', false),
('Jaguar', 'F-Pace', 2017, 2025, 'SVR', 4, 'performance', '5.0L Supercharged V8 (550hp)', '', 'Supercharged V8 ECM, adaptive suspension, Brembo brakes, sport exhaust, 550hp', '', true, 'Automatic', false),
('Jaguar', 'F-Type', 2014, 2025, 'Base', 3, 'premium', '2.0L Turbo I4', '', 'Turbo ECM, sport suspension, sport exhaust', 'Sports car.', true, 'Automatic', false),
('Jaguar', 'F-Type', 2014, 2025, 'R', 4, 'performance', '5.0L Supercharged V8 (550hp)', '', 'Supercharged V8 ECM, adaptive suspension, electronic LSD, Brembo, 550hp', '', true, 'Automatic', false),
('Jaguar', 'F-Type', 2014, 2025, 'SVR', 4, 'performance', '5.0L Supercharged V8 (575hp)', '', 'Supercharged V8 ECM, adaptive suspension, carbon fiber, Brembo, 575hp', '', true, 'Automatic', false),
('Land Rover', 'Range Rover', 2003, 2012, 'HSE', 3, 'premium', '4.4L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated/cooled leather, nav, park assist', 'L322.', false, 'Automatic', false),
('Land Rover', 'Range Rover', 2003, 2012, 'Supercharged', 4, 'performance', '4.2L Supercharged V8', 'Harman Kardon', 'Harman Kardon amp, supercharged V8 ECM, air suspension, adaptive suspension, 396hp', '', true, 'Automatic', false),
('Land Rover', 'Range Rover', 2013, 2022, 'HSE', 3, 'premium', '3.0L Supercharged V6', 'Meridian', 'Meridian amp, V6 ECM, air suspension, heated/cooled leather, nav, 360 camera', 'L405.', false, 'Automatic', false),
('Land Rover', 'Range Rover', 2013, 2022, 'Autobiography', 3, 'premium', '5.0L Supercharged V8', 'Meridian', 'Meridian amp, V8 ECM, air suspension, heated/cooled/massage seats, rear entertainment, every option', '', false, 'Automatic', false),
('Land Rover', 'Range Rover', 2013, 2022, 'SVAutobiography', 4, 'performance', '5.0L Supercharged V8 (565hp)', 'Meridian', 'Meridian amp, V8 ECM, adaptive air suspension, ceramic brakes, long wheelbase', '', true, 'Automatic', false),
('Land Rover', 'Range Rover Sport', 2005, 2013, 'HSE', 3, 'premium', '4.4L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated leather, nav', '', false, 'Automatic', false),
('Land Rover', 'Range Rover Sport', 2005, 2013, 'Supercharged', 4, 'performance', '5.0L Supercharged V8', 'Harman Kardon', 'Harman Kardon amp, supercharged V8 ECM, air suspension, 510hp', '', true, 'Automatic', false),
('Land Rover', 'Range Rover Sport', 2014, 2022, 'SE', 2, 'mid', '3.0L Supercharged V6', '', 'Air suspension, heated leather, nav', '', false, 'Automatic', false),
('Land Rover', 'Range Rover Sport', 2014, 2022, 'HSE', 3, 'premium', '3.0L Supercharged V6', 'Meridian', 'Meridian amp, air suspension, heated/cooled leather, adaptive cruise', '', false, 'Automatic', false),
('Land Rover', 'Range Rover Sport', 2014, 2022, 'SVR', 4, 'performance', '5.0L Supercharged V8 (575hp)', 'Meridian', 'Meridian amp, V8 ECM, adaptive air suspension, sport brakes, 575hp', '', true, 'Automatic', false),
('Land Rover', 'Discovery', 2017, 2025, 'SE', 2, 'mid', '3.0L Supercharged V6', '', 'Air suspension, heated leather, terrain response', '', false, 'Automatic', false),
('Land Rover', 'Discovery', 2017, 2025, 'HSE', 3, 'premium', '3.0L Supercharged V6', 'Meridian', 'Meridian amp, heated/cooled leather, adaptive cruise, 360 camera', '', false, 'Automatic', false),
('Land Rover', 'LR3', 2005, 2009, 'SE', 2, 'mid', '4.0L V6', '', 'Air suspension, heated leather, terrain response', '', false, 'Automatic', false),
('Land Rover', 'LR3', 2005, 2009, 'HSE', 3, 'premium', '4.4L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated leather, nav', '', false, 'Automatic', false),
('Land Rover', 'LR4', 2010, 2016, 'HSE', 3, 'premium', '5.0L V8', 'Harman Kardon', 'Harman Kardon amp, V8 ECM, air suspension, heated leather, nav, 360 camera', '', false, 'Automatic', false),
('Land Rover', 'Freelander', 2002, 2005, 'SE', 2, 'mid', '2.5L V6', '', 'Power seats, heated seats', '', false, 'Automatic', false),
('Land Rover', 'LR2', 2008, 2015, 'Base', 2, 'mid', '3.2L I6', '', 'Power seats, heated leather, panoramic moonroof', '', false, 'Automatic', false),
('Volvo', 'XC90', 2003, 2014, '2.5T', 2, 'mid', '2.5L Turbo I5', '', 'Turbo ECM, heated leather, moonroof, blind spot (late)', 'B5254T2 turbo I5.', false, 'Automatic', false),
('Volvo', 'XC90', 2003, 2014, 'V8', 3, 'premium', '4.4L V8', '', 'V8 ECM, heated leather, moonroof, park assist, Dynaudio possible', 'Yamaha-designed V8.', false, 'Automatic', false),
('Volvo', 'XC90', 2016, 2025, 'T5', 2, 'mid', '2.0L Turbo I4', '', 'Heated leather, panoramic moonroof, Pilot Assist', '', false, 'Automatic', false),
('Volvo', 'XC90', 2016, 2025, 'T6', 3, 'premium', '2.0L Turbo+Supercharged I4', 'Bowers & Wilkins', 'Bowers & Wilkins amp, twin-charged ECM, air suspension, heated/cooled leather, 360 camera, heads-up display', 'Both turbo AND supercharged. 316hp.', false, 'Automatic', false),
('Volvo', 'XC60', 2010, 2017, 'T5', 2, 'mid', '2.5L Turbo I5', '', 'Heated leather, moonroof, blind spot', '', false, 'Automatic', false),
('Volvo', 'XC60', 2010, 2017, 'T6', 3, 'premium', '3.0L Turbo I6', '', 'Turbo I6 ECM, heated leather, nav, park assist, adaptive cruise', '', false, 'Automatic', false),
('Volvo', 'XC60', 2018, 2025, 'T5', 2, 'mid', '2.0L Turbo I4', '', 'Heated leather, panoramic moonroof, Pilot Assist', '', false, 'Automatic', false),
('Volvo', 'XC60', 2018, 2025, 'T6', 3, 'premium', '2.0L Turbo+Supercharged I4', 'Bowers & Wilkins', 'Bowers & Wilkins amp, twin-charged ECM, heated/cooled leather, 360 camera', '', false, 'Automatic', false),
('Volvo', 'S60', 2001, 2009, '2.5T', 2, 'mid', '2.5L Turbo I5', '', 'Turbo ECM, heated leather', '', false, 'Automatic', false),
('Volvo', 'S60', 2001, 2009, 'T5', 3, 'premium', '2.5L Turbo I5 (300hp)', '', 'Turbo ECM (high output), sport suspension', '', false, 'Automatic', false),
('Volvo', 'S60', 2001, 2009, 'R', 4, 'performance', '2.5L Turbo I5 AWD (300hp)', '', 'R ECM, AWD, Brembo brakes, sport suspension, 300hp', 'S60R. AWD turbo. Cult Volvo.', true, 'Automatic', false),
('Buick', 'Century', 1997, 2005, 'Custom', 1, 'base', '3.1L V6', '', '', '', false, 'Automatic', false),
('Buick', 'Century', 1997, 2005, 'Limited', 3, 'premium', '3.1L V6', '', 'Heated leather, power seats, Concert Sound II', '', false, 'Automatic', false),
('Buick', 'Regal', 2011, 2017, 'Base', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Buick', 'Regal', 2011, 2017, 'Premium', 2, 'mid', '2.0L Turbo', '', 'Turbo ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Buick', 'Regal', 2011, 2017, 'GS', 4, 'performance', '2.0L Turbo (259hp)', '', 'GS turbo ECM, sport suspension, Brembo brakes, LSD, Recaro possible', 'Buick performance sedan. Sleeper.', false, 'Automatic', false),
('Buick', 'Lucerne', 2006, 2011, 'CX', 1, 'base', '3.8L V6', '', '', '', false, 'Automatic', false),
('Buick', 'Lucerne', 2006, 2011, 'CXL', 3, 'premium', '3.8L V6', '', 'Heated leather, power seats, dual climate', '', false, 'Automatic', false),
('Buick', 'Lucerne', 2006, 2011, 'Super', 4, 'performance', '4.6L V8 (292hp)', '', 'Northstar V8 ECM, magnetic ride, heated/cooled leather, 292hp', 'Northstar V8 Buick. Only V8 Buick sedan.', false, 'Automatic', false),
('Buick', 'Rendezvous', 2002, 2007, 'CX', 1, 'base', '3.4L V6', '', '', '', false, 'Automatic', false),
('Buick', 'Rendezvous', 2002, 2007, 'CXL', 3, 'premium', '3.6L V6', '', 'Heated leather, moonroof, rear entertainment possible', '', false, 'Automatic', false),
('Buick', 'Park Avenue', 1997, 2005, 'Base', 2, 'mid', '3.8L V6', '', 'Heated leather, power everything', '', false, 'Automatic', false),
('Buick', 'Park Avenue', 1997, 2005, 'Ultra', 3, 'premium', '3.8L Supercharged V6', '', 'Supercharged V6 ECM, heated leather, heads-up display, memory seats', 'Supercharged 3800.', false, 'Automatic', false),
('Ford', 'Five Hundred', 2005, 2007, 'SE', 1, 'base', '3.0L V6', '', '', 'Became Taurus 2008.', false, 'CVT', false),
('Ford', 'Five Hundred', 2005, 2007, 'SEL', 2, 'mid', '3.0L V6', '', 'Power seats, heated seats', '', false, 'CVT', false),
('Ford', 'Five Hundred', 2005, 2007, 'Limited', 3, 'premium', '3.0L V6', 'Audiophile', 'Audiophile amp, heated leather, moonroof, nav', '', false, 'CVT', false),
('Ford', 'Transit Connect', 2010, 2013, 'XL', 1, 'base', '2.0L I4', '', '', 'Cargo van.', false, 'Automatic', false),
('Ford', 'Transit Connect', 2010, 2013, 'XLT', 2, 'mid', '2.0L I4', '', 'Power windows, rear camera', 'Passenger van.', false, 'Automatic', false),
('Ford', 'Transit Connect', 2014, 2025, 'XL', 1, 'base', '2.5L I4', '', '', '', false, 'Automatic', false),
('Ford', 'Transit Connect', 2014, 2025, 'XLT', 2, 'mid', '2.5L I4', '', 'SYNC, rear camera, power windows', '', false, 'Automatic', false),
('Ford', 'Transit Connect', 2014, 2025, 'Titanium', 3, 'premium', '2.0L EcoBoost', '', 'EcoBoost ECM, heated leather, nav, park assist', 'Passenger van premium.', false, 'Automatic', false),
('Ford', 'Explorer Sport Trac', 2001, 2005, 'XLT', 2, 'mid', '4.0L V6', '', 'Power seats, cruise', 'Pickup version of Explorer.', false, 'Automatic', false),
('Ford', 'Explorer Sport Trac', 2001, 2005, 'XLS', 1, 'base', '4.0L V6', '', '', '', false, 'Automatic', false),
('Ford', 'Explorer Sport Trac', 2007, 2010, 'XLT', 2, 'mid', '4.0L V6', '', 'SYNC, power seats', '', false, 'Automatic', false),
('Ford', 'Explorer Sport Trac', 2007, 2010, 'Limited', 3, 'premium', '4.6L V8', 'Audiophile', 'Audiophile amp, V8 ECM, heated leather, moonroof, nav', '', false, 'Automatic', false),
('Ford', 'Explorer Sport Trac', 2007, 2010, 'Adrenalin', 3, 'premium', '4.6L V8', 'Audiophile', 'Audiophile amp, V8 ECM, sport suspension, leather, 20in wheels', '', false, 'Automatic', false),
('Dodge', 'Dart', 2013, 2016, 'SE', 1, 'base', '2.0L I4', '', '', '', false, 'Automatic', false),
('Dodge', 'Dart', 2013, 2016, 'SXT', 2, 'mid', '2.4L I4', '', 'Heated seats, Uconnect, rear camera', '', false, 'Automatic', false),
('Dodge', 'Dart', 2013, 2016, 'GT', 3, 'premium', '2.4L I4', 'Alpine', 'Alpine amp, sport suspension, heated leather, nav, moonroof', '', false, 'Automatic', false),
('Dodge', 'Dart', 2013, 2016, 'Rallye', 2, 'mid', '1.4L Turbo', '', 'Turbo ECM, sport appearance', '', true, 'Automatic', false),
('Dodge', 'Nitro', 2007, 2011, 'SE', 1, 'base', '3.7L V6', '', '', '', false, 'Automatic', false),
('Dodge', 'Nitro', 2007, 2011, 'SXT', 2, 'mid', '3.7L V6', '', 'Power seats, heated seats', '', false, 'Automatic', false),
('Dodge', 'Nitro', 2007, 2011, 'R/T', 3, 'premium', '4.0L V6', 'Infinity', 'Infinity amp, V6 ECM, heated leather, moonroof, chrome', '', false, 'Automatic', false),
('Mitsubishi', 'Galant', 2004, 2012, 'DE', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Mitsubishi', 'Galant', 2004, 2012, 'ES', 2, 'mid', '2.4L I4', '', 'Power seats, heated seats possible', '', false, 'Automatic', false),
('Mitsubishi', 'Galant', 2004, 2012, 'Ralliart', 3, 'premium', '3.8L V6 (258hp)', '', 'V6 ECM, sport suspension, sport exhaust, paddle shifters', 'V6 sport sedan. 258hp.', false, 'Automatic', false),
('Toyota', 'Solara', 1999, 2003, 'SE', 2, 'mid', '2.4L I4', '', 'Power seats, moonroof', 'Camry coupe.', false, 'Automatic', false),
('Toyota', 'Solara', 1999, 2003, 'SLE', 3, 'premium', '3.3L V6', 'JBL', 'JBL amp, V6 ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Toyota', 'Solara', 2004, 2008, 'SE', 2, 'mid', '2.4L I4', '', 'Power seats, moonroof', '', false, 'Automatic', false),
('Toyota', 'Solara', 2004, 2008, 'SLE', 3, 'premium', '3.3L V6', 'JBL', 'JBL amp, V6 ECM, heated leather, nav, moonroof', '', false, 'Automatic', false),
('Kia', 'Rio', 2001, 2005, 'Base', 1, 'base', '1.6L I4', '', '', '', false, 'Automatic', false),
('Kia', 'Rio', 2006, 2011, 'LX', 1, 'base', '1.6L I4', '', '', '', false, 'Automatic', false),
('Kia', 'Rio', 2012, 2017, 'LX', 1, 'base', '1.6L I4', '', '', '', false, 'Automatic', false),
('Kia', 'Rio', 2012, 2017, 'SX', 2, 'mid', '1.6L I4', '', 'Heated seats, moonroof, push-button start', '', false, 'Automatic', false),
('Kia', 'Rio', 2018, 2025, 'LX', 1, 'base', '1.6L I4', '', '', '', false, 'Automatic', false),
('Kia', 'Rio', 2018, 2025, 'S', 2, 'mid', '1.6L I4', '', 'Heated seats, rear camera', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2003, 2008, 'i', 1, 'base', '2.3L I4', '', '', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2003, 2008, 's', 3, 'premium', '3.0L V6', 'Bose', 'Bose amp, V6 ECM, heated leather, moonroof', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2003, 2008, 'Mazdaspeed6', 4, 'performance', '2.3L Turbo AWD', 'Bose', 'Bose amp, DISI turbo ECM, AWD transfer case, turbo, intercooler, LSD', 'Already in reference but linking.', true, '6-speed Manual', false),
('Mazda', 'Mazda6', 2009, 2013, 'i Sport', 1, 'base', '2.5L I4', '', '', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2009, 2013, 'i Grand Touring', 3, 'premium', '2.5L I4', 'Bose', 'Bose amp, heated leather, moonroof, blind spot', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2014, 2021, 'Sport', 1, 'base', '2.5L I4', '', '', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2014, 2021, 'Touring', 2, 'mid', '2.5L I4', '', 'Heated leather, blind spot, rear camera', '', false, 'Automatic', false),
('Mazda', 'Mazda6', 2014, 2021, 'Grand Touring', 3, 'premium', '2.5L Turbo', 'Bose', 'Bose amp, turbo ECM, heated/ventilated leather, nav, heads-up display', '2018+. Turbo.', false, 'Automatic', false),
('Mazda', 'Mazda6', 2014, 2021, 'Signature', 3, 'premium', '2.5L Turbo', 'Bose', 'Bose amp, turbo ECM, Nappa leather, heated/ventilated seats, nav', '2019+.', false, 'Automatic', false),
('Mazda', 'Mazda5', 2006, 2010, 'Sport', 1, 'base', '2.3L I4', '', '', 'Mini minivan.', false, 'Automatic', false),
('Mazda', 'Mazda5', 2006, 2010, 'Grand Touring', 3, 'premium', '2.3L I4', 'Bose', 'Bose amp, heated leather, moonroof', '', false, 'Automatic', false),
('Mazda', 'Mazda5', 2012, 2015, 'Sport', 1, 'base', '2.5L I4', '', '', '', false, 'Automatic', false),
('Mazda', 'Mazda5', 2012, 2015, 'Grand Touring', 3, 'premium', '2.5L I4', 'Bose', 'Bose amp, heated leather, moonroof', '', false, 'Automatic', false),
('Mazda', 'CX-7', 2007, 2012, 'Sport', 1, 'base', '2.5L I4', '', '', '2010+ I4 base.', false, 'Automatic', false),
('Mazda', 'CX-7', 2007, 2012, 'Touring', 2, 'mid', '2.3L Turbo', '', 'Turbo ECM, heated leather, moonroof possible', 'DISI turbo. Same as Mazdaspeed3.', false, 'Automatic', false),
('Mazda', 'CX-7', 2007, 2012, 'Grand Touring', 3, 'premium', '2.3L Turbo', 'Bose', 'Bose amp, turbo ECM, heated leather, nav, moonroof', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 1998, 2010, 'GL', 1, 'base', '2.0L I4', '', '', 'New Beetle.', false, 'Automatic', false),
('Volkswagen', 'Beetle', 1998, 2010, 'GLS', 2, 'mid', '1.8L Turbo', '', 'Turbo ECM, heated seats, moonroof possible', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 1998, 2010, 'Turbo S', 3, 'premium', '1.8L Turbo (180hp)', '', 'Turbo ECM (high output), sport suspension, 18in wheels, Recaro possible', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 2012, 2019, '2.5', 1, 'base', '2.5L I5', '', '', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 2012, 2019, 'Turbo', 2, 'mid', '2.0L Turbo', 'Fender', 'Fender amp possible, turbo ECM, heated seats', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 2012, 2019, 'Turbo R-Line', 3, 'premium', '2.0L Turbo', 'Fender', 'Fender amp, turbo ECM, sport suspension, 19in wheels, bi-xenon headlights', '', false, 'Automatic', false),
('Volkswagen', 'Beetle', 2012, 2019, 'TDI', 3, 'premium', '2.0L TDI Diesel', 'Fender', 'Fender amp, TDI ECM, turbo, DPF, heated seats', 'Dieselgate.', false, 'Automatic', true),
('GMC', 'Envoy', 2002, 2009, 'SLE', 1, 'base', '4.2L I6', '', '', 'Atlas I6. Trailblazer twin.', false, 'Automatic', false),
('GMC', 'Envoy', 2002, 2009, 'SLT', 3, 'premium', '4.2L I6', 'Bose', 'Bose amp, heated leather, moonroof, power liftgate', '', false, 'Automatic', false),
('GMC', 'Envoy', 2002, 2009, 'Denali', 3, 'premium', '5.3L V8', 'Bose', 'Bose amp, V8 ECM, heated/cooled leather, nav', 'V8 only on Denali.', false, 'Automatic', false),
('Jeep', 'Commander', 2006, 2010, 'Sport', 1, 'base', '3.7L V6', '', '', 'Grand Cherokee platform with 3rd row.', false, 'Automatic', false),
('Jeep', 'Commander', 2006, 2010, 'Limited', 3, 'premium', '5.7L HEMI', 'Infinity', 'Infinity amp, HEMI ECM, heated leather, nav, moonroof, rear entertainment', '', false, 'Automatic', false),
('Jeep', 'Commander', 2006, 2010, 'Overland', 3, 'premium', '5.7L HEMI', 'Infinity', 'Infinity amp, HEMI ECM, heated leather, nav, moonroof, Quadra-Drive II', '', false, 'Automatic', false),
('Subaru', 'Impreza', 2002, 2007, '2.5 RS', 2, 'mid', '2.5L H4', '', 'Sport suspension, alloy wheels', 'Not WRX. But GC/GD chassis is cult.', true, 'Automatic', false),
('Subaru', 'Impreza', 2008, 2014, '2.0i', 1, 'base', '2.0L H4', '', '', '', false, 'CVT', false),
('Subaru', 'Impreza', 2008, 2014, '2.0i Premium', 2, 'mid', '2.0L H4', '', 'Heated seats, moonroof', '', false, 'CVT', false),
('Subaru', 'Impreza', 2008, 2014, '2.0i Limited', 3, 'premium', '2.0L H4', '', 'Heated leather, moonroof, nav, EyeSight', '', false, 'CVT', false),
('Subaru', 'Impreza', 2017, 2025, '2.0i', 1, 'base', '2.0L H4', '', '', '', false, 'CVT', false),
('Subaru', 'Impreza', 2017, 2025, 'Premium', 2, 'mid', '2.0L H4', '', 'EyeSight, heated seats, moonroof', '', false, 'CVT', false),
('Mercury', 'Sable', 2000, 2005, 'GS', 1, 'base', '3.0L V6', '', '', 'Taurus twin.', false, 'Automatic', false),
('Mercury', 'Sable', 2000, 2005, 'LS', 2, 'mid', '3.0L V6', '', 'Heated leather, moonroof, power seats', '', false, 'Automatic', false),
('Mercury', 'Sable', 2008, 2009, 'Base', 1, 'base', '3.5L V6', '', '', 'Last Sable. Taurus twin.', false, 'Automatic', false),
('Mercury', 'Sable', 2008, 2009, 'Premier', 3, 'premium', '3.5L V6', '', 'Heated leather, moonroof, SYNC', '', false, 'Automatic', false),
('Chevrolet', 'C1500', 1988, 1998, 'Cheyenne', 1, 'base', '4.3L V6', '', '', 'GMT400. Pre-Silverado name.', false, 'Automatic', false),
('Chevrolet', 'C1500', 1988, 1998, 'Silverado', 2, 'mid', '5.7L V8', '', 'Power windows, cruise, A/C', '350 V8.', false, 'Automatic', false),
('Chevrolet', 'C1500', 1988, 1998, 'SS 454', 4, 'performance', '7.4L V8 (454)', '', '454 V8 ECM, sport suspension, 255hp', 'Big block truck. Rare.', true, 'Automatic', false),
('Mitsubishi', 'Montero Sport', 1997, 2004, 'ES', 1, 'base', '2.4L I4', '', '', '', false, 'Automatic', false),
('Mitsubishi', 'Montero Sport', 1997, 2004, 'LS', 2, 'mid', '3.0L V6', '', 'V6 ECM, power seats', '', false, 'Automatic', false),
('Mitsubishi', 'Montero Sport', 1997, 2004, 'XLS', 3, 'premium', '3.5L V6', '', 'V6 ECM, heated leather, moonroof, rear diff lock', '', false, 'Automatic', false);

-- Total: 218 entries
-- Makes: 23
-- Models: 71
-- Cult: 27
-- Diesel: 1
